### ISSUE TITLE
[要望]Sansanプラグイン 

### ISSUE THREAD

**Issue by north-river** [kintone/plugin-sdk#16]
人IDと会社IDでも検索可能にする。

**Comment by north-river** [comment]
@masaya-chikamoto さん
余裕あるときにプルリクお待ちしております～

**Comment by masaya-chikamoto** [comment]
@north-river 
了解しました！

**Comment by masaya-chikamoto** [comment]
@north-river 
こちらのIssueについてですが、人ID（人物ID）についてはプルリクの方で対応済みです。
会社IDについては取得できないようでしたのでこちらのIssueをクローズでお願い致します。
