### ISSUE TITLE
[Vote Plug-in] Don't copy users who liked the record when duplicating

### ISSUE THREAD

**Issue by ydambara** [kintone/plugin-sdk#54]
・現象
レコード再利用時にいいね！数といいね！している人が「引き継がれる」

・改修案
レコード再利用時にいいね！数といいね！している人が「引き継がれない」

**Comment by will-yama** [comment]
Translation:
When a record is duplicated, it also copies the data of the users who liked the record.
It would be better if this data was not copied.

**Comment by will-yama** [comment]
I confirmed that with the latest version of this plug-in, this issue has already been fixed.
