### ISSUE TITLE
条件書式V2 日付について

### ISSUE THREAD

**Issue by soronga** [kintone/plugin-sdk#70]
お世話になっております。
初心者です。
https://developer.cybozu.io/hc/ja/articles/208236353-%E6%96%B0%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E7%89%88-%E6%9D%A1%E4%BB%B6%E6%9B%B8%E5%BC%8F%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3
を使用しております。
「提出期限」と日付型のレコードがあります。

これで①この日の５日前なら「背景：黄色」

　　　②この日の3日前なら「背景：黄色、文字：赤」

　　　③この日を過ぎたら「文字：赤」

ぜひご教授お願い致します。

**Comment by will-yama** [comment]
こんにちは。
プラグインの使い方に関してはissueではなく、上記のリンク先のコメント又はdeveloper network の[コミュニティ](https://developer.cybozu.io/hc/ja/community/topics)にてお願いします m(_ _)m
また、トラブルシューティング用に現在の設定のスクリーンショットも添付して頂けると解決がしやすいので、よろしくお願いします。
