### ISSUE TITLE
条件書式V2 一覧編集の不具合

### ISSUE THREAD

**Issue by north-river** [kintone/plugin-sdk#8]
フィールド一覧から編集ボタンを押す→編集を終了すると、色がデフォルトのままになってしまいます。 
更新したり、ソートしなおすと直りますが、少し気になります。フィールド一覧から編集ボタンを押す→編集を終了すると、色がデフォルトのままになります。

**Comment by masaya-chikamoto** [comment]
こちら確認したところ、
(i)レコード一覧画面で編集⇒保存をクリック時
(ii)レコード一覧画面で編集⇒キャンセルをクリック時
どちらの場合も書式変更された要素が削除されてしまうため、
制限事項の第3項目に記載されている通り、仕様となります。

**Comment by north-river** [comment]
では、こちらは対応しないということでissueをとじます
